services:
  demo:
  wms:
    versions: ['1.3.0']
    srs: ['EPSG:26911']
    image_formats: ['image/jpeg', 'image/png']

    md:
      title: MapProxy WMS Proxy
      abstract: This is the fantastic MapProxy.
      online_resource: http://mapproxy.org/
      contact:
        person: Christopher Swingley
        email: cswingle@swingleydev.com
      access_constraints:
        The data is licensed as Creative Commons Attribution-Share Alike 2.0
        (http://creativecommons.org/licenses/by-sa/2.0/)
      fees: 'None'
  wmts:
    restful: true
    restful_template: '/{Layer}/{TileMatrixSet}/{TileMatrix}/{TileCol}/{TileRow}.{Format}'
    kvp: true

layers:
  - name: quads_150dpi
    title: USGS 7.5m quads, 150dpi
    sources: [wms_cache]
  - name: quads_300dpi
    title: USGS 7.5m quads, 300dpi
    sources: [wms_cache_300]

caches:
  wms_cache:
    grids: [utm11n]
    sources: [emigrant_wms]
    format: image/jpeg
    request_format: image/jpeg
  wms_cache_300:
    grids: [utm11n]
    sources: [emigrant_wms]
    format: image/jpeg
    request_format: image/jpeg

sources:
  emigrant_wms:
    type: wms
    req:
      url: https://swingleydev.com/cgi-bin/mapserv?
      layers: quads_150dpi,quads_300dpi
      map: emigrant.map
    supported_srs: ['EPSG:26911']

grids:
  utm11n:
    tile_size: [256, 256]
    srs: 'EPSG:26911'
    bbox: [225080.237, 4194543.883, 292596.847, 4252111.328]
    bbox_srs: 'EPSG:26911'
    origin: 'ul'
    # source raster resolution * or / by sqrt(2):
    res: [32.48, 22.97, 16.24, 11.48, 8.12, 5.74, 4.06, 2.87, 2.03]

globals:
    http:
        ssl_ca_certs: /etc/ssl/certs/ca-certificates.crt
    image:
        resampling_method: bicubic # best for vector
